from typing import Any

from polars import Date, Float32, Float64, Int32, String, UInt16, UInt32

dimdaf_schema: dict[str, Any] = {
    "nro_persona": UInt32,
    "persona_key": UInt32,
    "cuit": String,
    "nro_documento": String,
    "sexo": String,
    "nombre": String,
    "domicilio": String,
    "cp": String,
    "cp_sufijo": String,
    "bloqueado": UInt16,
    "es_delegado": UInt16,
}


primas_ramas_varias_schema: dict[str, Any] = {
    "femision": Date,
    "fvigdesde": Date,
    "fvighasta": Date,
    "op": UInt32,
    "cod_rama": UInt32,
    "poliza": UInt32,
    "suplemento": UInt32,
    "componente": UInt32,
    "cod_organizador": UInt32,
    "cod_poductor": UInt32,
    "cod_riesgo": UInt32,
    "riesgo": String,
    "cod_cobertura": UInt32,
    "cobertura": String,
    "cod_provincia": String,
    "sa_cobertura": Float32,
    "premio_bruto_suplemento": Float32,
    "bon_prima_porc": Float32,
    "pormilaje": Float32,
    "prima_tarifa_suplemento": Float32,
    "prima_tarifa_cobertura": Float32,
    "prima_neta_suplemento": Float32,
    "prima_neta_cobertura": Float32,
}


primas_automotores_schema: dict[str, Any] = {
    "femision": Date,
    "fvigdesde": Date,
    "fvighasta": Date,
    "op": UInt32,
    "componente": UInt32,
    "suplemento": UInt32,
    "cod_rama": UInt32,
    "poliza": UInt32,
    "aa_componente": Float64,
    "cap": UInt32,
    "var": UInt32,
    "air": UInt32,
    "origen": String,
    "anio_componente": UInt32,
    "cod_cobertura_aut": String,
    "cod_tipo_veh": UInt32,
    "cod_uso_veh": UInt32,
    "prima_tarifa_suplemento": Float64,
    "bon_prima_suplemento": Float64,
    "premio_suplemento": Float64,
    "premio_cobrado_suplemento": Float64,
    "cod_organizador": UInt32,
    "cod_productor": UInt32,
    "prima_tarifa_componente": Float64,
    "prima_rc_tarifa_componente": Float64,
    "prima_casco_tarifa_componente": Float64,
    "prima_neta_componente": Float64,
    "prima_rc_neta_componente": Float64,
    "prima_casco_neta_componente": Float64,
}


dim_coberturas_ramas_varias_schema: dict[str, Any] = {
    "cod_rama": UInt32,
    "cod_cobertura": UInt32,
    "cobertura": String,
    "pormilaje": Float32,
    "informe": String,
    "fd": Date,
    "fh": Date,
}


dim_localidades_schema: dict[str, Any] = {
    "cp": UInt32,
    "cp_sufijo": UInt32,
    "localidad": String,
    "cod_provincia": String,
    "cod_prov_inder": UInt32,
    "provincia": String,
}


dim_rcs_aut_schema: dict[str, Any] = {
    "num_tarifa": UInt32,
    "cap": UInt32,
    "var": UInt32,
    "rcsl": Float32,
    "rccl": Float32,
    "ecext": Float32,
    "rcap": Float32,
    "rcobl": Float32,
    "fecha_desde": Date,
}


dinm_tasas_aut_schema: dict[str, Any] = {
    "num_tarifa": UInt32,
    "cap": UInt32,
    "air": UInt32,
    "cod_cobertura": String,
    "segmento_ant": UInt32,
    "ant_minima": UInt32,
    "ant_maxima": UInt32,
    "tasa_anual": Float32,
    "fecha_desde": Date,
}


sehpn151_schema: dict[str, Any] = {
    "op": UInt32,
    "suplemento": UInt32,
    "cod_tipo_op": UInt32,
    "cod_subtipo_op": UInt32,
    "pol_vida_nva_ren": UInt32,
    "cod_rama": UInt32,
    "poliza": UInt32,
    "nro_asegurado": UInt32,
    "cp_asegurado": UInt32,
    "cp_sufijo_asegurado": UInt32,
    "nom_asegurado": String,
    "localidad_asegurado": String,
    "provincia_asegurado": String,
    "cod_organizador": UInt32,
    "cod_productor": UInt32,
    "suma_asegurada_generada": Float64,
    "prima_neta": Float64,
    "rec_financiero": Float64,
    "rec_Administrativo": Float64,
    "derecho_emision": Float64,
    "sell_riesgo": Float64,
    "impuestos_interno": Float64,
    "serv_sociales": Float64,
    "tasa_ssn": Float64,
    "iva": Float64,
    "iva_percepcion": Float64,
    "iva_resp_no_inscr": Float64,
    "bonif_prima": Float64,
    "acc": Float64,
    "rec_capital": Float64,
    "femision": Date,
    "fvig_desde": Date,
    "fvig_hasta": Date,
    "prima_tarifa": Float64,
    "premio_bruto": Float64,
    "cod_organizador_comision": UInt32,
    "com_organizador": Float64,
    "cod_productor_comision": UInt32,
    "com_productor": Float64,
}


sinpag_schema: dict[str, Any] = {
    "cod_rama": UInt32,
    "nro_siniestro": UInt32,
    "nro_liquidacion": UInt32,
    "cod_item_pago": String,
    "fecha_pago": Date,
    "cod_causa": UInt32,
    "nro_asegurado": UInt32,
    "cod_organizador": UInt32,
    "cod_productor": UInt32,
    "tipo_movimiento": String,
    "tipo_liquidacion": String,
    "clase_reserva": UInt32,
    "tipo_acreedor": String,
    "cod_acreedor": UInt32,
    "cod_mayor_auxiliar": String,
    "nro_mayor_auxiliar": UInt32,
    "pagado": String,
    "proceso": String,
    "estado_ingreso": String,
    "cant_frentes": UInt32,
    "op": UInt32,
    "nro_beneficiario": UInt32,
    "tipo_reserva": String,
    "cod_riesgo": String,
    "cobertura_reservada": UInt32,
    "item_pago": String,
    "fecha_denuncia": Date,
    "fecha_ocurrencia": Date,
    "direccion_siniestro": String,
    "cp_siniestro": UInt32,
    "marca_fuera_termino": String,
    "cod_terminado": String,
    "cod_ubicacion": String,
    "fuera_vigencia": String,
    "poliza_anulada": String,
    "en_caducidad": String,
    "componente_baja": String,
    "conductor": UInt32,
    "cond_habitual": String,
    "poliza": UInt32,
    "suplemento": UInt32,
    "componente": UInt32,
    "cod_cobertura_aut": String,
    "suma_asegurada_aut": Float32,
    "cod_inder_prov_aut": UInt32,
    "cod_marca_aut": String,
    "cod_modelo_aut": String,
    "anio_vehiculo_aut": UInt32,
    "origen_vehiculo_aut": String,
    "cod_tipo_vehiculo_aut": UInt32,
    "cod_uso_vehiculo_aut": UInt32,
    "importe": Float32,
}


vigentes_vehiculos_dia: dict[str, Any] = {
    "cod_organizador": UInt32,
    "cod_productor": UInt32,
    "cod_rama": UInt32,
    "poliza": UInt32,
    "suplemento": UInt32,
    "componente": UInt32,
    "f_vig_desde": Date,
    "f_vig_hasta": Date,
    "nro_asegurado": UInt32,
    "nom_asegurado": String,
    "cp_asegurado": UInt32,
    "cp_sufijo_asegurado": UInt32,
    "cod_marca": String,
    "cod_modelo": String,
    "cod_submodelo": String,
    "marca": String,
    "modelo": String,
    "submodelo": String,
    "cva_capitulo": UInt32,
    "cva_variante": UInt32,
    "cva_descripcion": String,
    "anio_vehiculo": UInt32,
    "cod_usovehiculo": UInt32,
    "cod_tipovehiculo": UInt32,
    "cod_coberturaaut": String,
    "suma_asegurada": Float32,
    "nro_motor": String,
    "nro_chasis": String,
    "origen": String,
    "nro_persona_pagador": UInt32,
    "nro_persona_tomador": UInt32,
    "cod_carroceria": String,
    "cp_productor": UInt32,
    "cp_sufijo_productor": UInt32,
    "localidad_productor": String,
    "cod_provincia_productor": String,
    "provincia_productor": String,
    "cod_provincia_inder_productor": UInt32,
    "tarifa_madre_letra": String,
    "tarifa_hija": UInt32,
    "dominio": String,
    "ant_vehiculo": Int32,
    "fecha": Date,
}


organizadores_schema: dict[str, Any] = {
    "cod_organizador": UInt32,
    "nro_persona": UInt32,
    "nombre": String,
    "domicilio": String,
    "cp": UInt32,
    "cp_sufijo": UInt32,
    "localidad": String,
    "cod_provincia": String,
    "tipo_doc": String,
    "nro_doc": UInt32,
    "cuit": String,
    "provincia": String,
    "cod_inder_provincia": String,
    "matricula": UInt32,
    "cod_grupo": UInt32,
    "grupo": String,
}


dim_coberturas_aut_schema: dict[str, Any] = {
    "cod_cobertura": String,
    "or_cobertura": UInt32,
    "cat_cobertura": String,
    "or_cat_cobertura": UInt32,
    "rt": UInt16,
    "rp": UInt16,
    "it": UInt16,
    "ip": UInt16,
    "at": UInt16,
    "ap": UInt16,
}
